"""empty message

Revision ID: 5201c95b33ef
Revises: 
Create Date: 2020-03-29 12:13:35.972069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5201c95b33ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('words', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comment', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.create_index(op.f('ix_comment_book_id'), 'comment', ['book_id'], unique=False)
    op.create_index(op.f('ix_comment_content'), 'comment', ['content'], unique=False)
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comment_title'), 'comment', ['title'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comment', 'comment', ['replied_id'], ['id'])
    op.create_index(op.f('ix_note_book_id'), 'note', ['book_id'], unique=False)
    op.create_index(op.f('ix_note_content'), 'note', ['content'], unique=False)
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    op.create_index(op.f('ix_note_title'), 'note', ['title'], unique=False)
    op.create_index(op.f('ix_note_user_id'), 'note', ['user_id'], unique=False)
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'note', 'book', ['book_id'], ['id'])
    op.drop_index(op.f('ix_note_user_id'), table_name='note')
    op.drop_index(op.f('ix_note_title'), table_name='note')
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_index(op.f('ix_note_content'), table_name='note')
    op.drop_index(op.f('ix_note_book_id'), table_name='note')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'book', ['book_id'], ['id'])
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_title'), table_name='comment')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_index(op.f('ix_comment_content'), table_name='comment')
    op.drop_index(op.f('ix_comment_book_id'), table_name='comment')
    op.alter_column('comment', 'title',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_table('sensitive_words')
    # ### end Alembic commands ###
